'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import type { investigateMunicipal } from '../../lib/municipal/investigation';
const RoomView = dynamic(() => import('./room-view'), { ssr: false });
type Result = Awaited<ReturnType<typeof investigateMunicipal>>;

export default function MunicipalDemo({ spatialEnabled }: { spatialEnabled: boolean }) {
  const [mode, setMode] = useState<'live' | 'snapshot' | 'synthetic'>('live');
  const [model, setModel] = useState<'scripted' | 'gpt-6-astra'>('gpt-6-astra');
  const [spatial, setSpatial] = useState(spatialEnabled), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const [result, setResult] = useState<Result | null>(null), [liveEvents, setLiveEvents] = useState<Result['events']>([]);
  const [liveGraph, setLiveGraph] = useState<NonNullable<Result['spatialGraph']> | null>(null), [liveSpatialEvidence, setLiveSpatialEvidence] = useState<Result['evidence']>([]);
  const [selected, setSelected] = useState<string | null>(null), [selectedRoom, setSelectedRoom] = useState<string | null>(null);
  const activeGraph = result?.spatialGraph ?? liveGraph, activeEvidence = result?.evidence ?? liveSpatialEvidence, activeFindings = result?.findings ?? [];
  const spatialObservation = activeEvidence.find(item => item.sourceType === 'spatial_observation');
  const hasPermitFollowup = liveEvents.some(event => ['get_permit_history', 'search_permits'].includes(event.tool));
  const stage = result ? 4 : activeGraph ? 3 : liveEvents.some(event => event.tool === 'record_spatial_graph') ? 2 : liveEvents.length ? 1 : 0;
  useEffect(() => { if (!selectedRoom && activeGraph) setSelectedRoom(activeGraph.rooms.find(room => room.id === 'kitchen')?.id ?? activeGraph.rooms[0]?.id ?? null); }, [activeGraph, selectedRoom]);
  async function run() {
    setBusy(true); setError(''); setResult(null); setSelected(null); setSelectedRoom(null); setLiveEvents([]); setLiveGraph(null); setLiveSpatialEvidence([]);
    try { const response = await fetch('/api/municipal', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ dataMode: mode, model, spatial, stream: true }) }); if (!response.ok) { const body = await response.json(); throw new Error(body.error?.message || 'Request failed.'); } if (!response.body) throw new Error('Investigation stream unavailable.'); const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = '';
      while (true) { const chunk = await reader.read(); if (chunk.done) break; buffer += decoder.decode(chunk.value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() || ''; for (const line of lines.filter(Boolean)) { const item = JSON.parse(line); if (item.type === 'event') { setLiveEvents(events => [...events, item.event]); if (item.event.spatialGraph) setLiveGraph(item.event.spatialGraph); if (item.event.spatialEvidence) setLiveSpatialEvidence(item.event.spatialEvidence); } if (item.type === 'result') setResult(item.result); if (item.type === 'error') throw new Error(item.error.message); } }
    } catch (e) { setError(e instanceof Error ? e.message : 'Request failed.'); } finally { setBusy(false); }
  }
  return <main className="demo-shell">
    <header className="site-header"><Link href="/">UNDER THE ROOF</Link><span>ASTRA INVESTIGATIONS</span></header>
    <section className="demo-hero"><div><p className="eyebrow">ACT I · INVESTIGATE</p><h1>Beyond the<br /><em>listing price.</em></h1><p className="intro">Astra investigates one Philadelphia property across its public record and physical evidence.</p></div><div className="property-card"><p className="eyebrow">PROPERTY</p><h2>2020 Delancey Place</h2><p>Philadelphia, PA · OPA parcel 081035500</p><span className="status-dot">{busy ? 'LIVE INVESTIGATION' : result ? 'INVESTIGATION COMPLETE' : 'READY FOR INVESTIGATION'}</span></div></section>
    <section className="demo-path" aria-label="Investigation path">{[['PROPERTY', '2020 Delancey'], ['ASTRA', 'Live investigation'], ['SPATIAL GRAPH', activeGraph ? 'Model created' : 'Waiting for visual evidence'], ['MUNICIPAL RECORDS', hasPermitFollowup ? 'Permit follow-up' : 'Astra selects next'], ['BUYER FINDING', result ? 'Grounded result' : 'Reconciling evidence']].map(([title, detail], index) => <div className={stage >= index ? 'path-step active' : 'path-step'} key={title}><span>{String(index + 1).padStart(2, '0')}</span><strong>{title}</strong><small>{detail}</small></div>)}</section>
    <section className="control-strip"><div><label htmlFor="data-mode">Evidence source</label><select id="data-mode" disabled={busy} value={mode} onChange={e => setMode(e.target.value as typeof mode)}><option value="live">Live Philadelphia public API</option><option value="snapshot">Dated public snapshot</option><option value="synthetic">Explicit synthetic scenario</option></select></div><div><label htmlFor="model">Investigator</label><select id="model" disabled={busy} value={model} onChange={e => setModel(e.target.value as typeof model)}><option value="gpt-6-astra">Live GPT-6 Astra</option><option value="scripted">Scripted contract demo</option></select></div><label className="spatial-toggle"><input type="checkbox" disabled={busy || !spatialEnabled} checked={spatial} onChange={e => setSpatial(e.target.checked)} /> Multimodal spatial analysis <small>recommended</small></label><button className="primary-cta compact" disabled={busy} onClick={run}>{busy ? 'Astra is investigating…' : 'Start investigation →'}</button></section>
    <p className="note demo-disclosure">Public records are real or dated snapshots according to the selected source. The floor plan and kitchen reference image are synthetic demo imagery; Astra multimodal analysis and the spatial graph are live.</p>
    {error && <p role="alert" className="error">{error}</p>}
    {(busy || liveEvents.length > 0) && <section className="investigation-panel" aria-label="Live investigation trace"><div className="section-heading"><div><p className="eyebrow">LIVE INVESTIGATION TRACE</p><h2>Astra follows the evidence.</h2></div><span className="live-pill">{busy ? '● LIVE' : 'COMPLETE'}</span></div><div className="trace-grid">{liveEvents.map(event => <div key={event.sequence} className={`trace-item ${event.phase}`}><span className="trace-mark">{event.phase === 'completed' ? '✓' : event.phase === 'failed' ? '!' : event.phase === 'rejected' ? '↻' : '·'}</span><div><strong>{event.label.replace(/\.\.\.$/, '')}</strong>{event.phase === 'completed' && <small>Evidence collected</small>}{event.phase === 'failed' && <small>Source unavailable</small>}{event.phase === 'rejected' && <small>Correcting evidence</small>}</div></div>)}</div>{busy && <p className="private-note">Astra’s tool actions are visible; internal reasoning stays private.</p>}</section>}
    {activeGraph && <section className="reconstruct-section" aria-label="AI reconstructed spatial evidence"><div className="section-heading"><div><p className="eyebrow">ACT II · RECONSTRUCT / REASON</p><h2>Astra turns images into space.</h2></div><span className="model-badge">AI-RECONSTRUCTED SPATIAL MODEL</span></div><div className="model-intro"><p>Generated from Astra multimodal analysis</p><span>Approximate · Not to scale</span></div><RoomView graph={activeGraph} evidence={activeEvidence} findings={activeFindings} selected={selected} selectedRoom={selectedRoom} onSelect={id => { setSelected(id); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }} onSelectRoom={area => { setSelectedRoom(area); const finding = activeFindings.find(item => item.areaIds.includes(area)); if (finding) { setSelected(finding.id); setSelectedRoom(area); } }} /><div className="evidence-bridge"><span>Floor plan + image</span><b>→</b><span>Astra spatial observation</span><b>→</b><span className={hasPermitFollowup ? 'active' : ''}>Permit investigation</span><b>→</b><span>Buyer finding</span></div>{spatialObservation && <div className="observation-callout"><span className="callout-icon">✦</span><div><p className="eyebrow">ASTRA OBSERVATION · {spatialObservation.areaIds?.join(', ')}</p><p>{spatialObservation.content}</p>{hasPermitFollowup && <small>Spatial evidence prompted Astra to investigate renovation records.</small>}</div></div>}</section>}
    {(result || (activeGraph && !busy)) && <section className="findings-section" aria-label="Buyer findings"><div className="section-heading"><div><p className="eyebrow">ACT III · FINDINGS</p><h2>What a buyer should ask next.</h2></div><p className="note">{result ? `${result.findings.length} grounded finding${result.findings.length === 1 ? '' : 's'} · ${result.toolCalls} tool actions` : 'Reconciling evidence…'}</p></div><div className="finding-grid">{activeFindings.slice(0, 3).map(f => <article className="finding-card" id={f.id} key={f.id} style={selected === f.id ? { borderColor: '#b38742' } : undefined}><div className="finding-top"><span className="finding-kind">{f.areaIds.length ? 'RENOVATION / ' + f.areaIds[0].toUpperCase() : 'OWNERSHIP COST'}</span><span>{f.confidence} confidence</span></div><h3>{f.title}</h3><h4>Fact</h4><p className="facts">{f.fact.split('\n')[0]}</p><h4>Inference</h4><p>{f.inference}</p><h4>Buyer action</h4><p>{f.recommendedAction}</p><div className="finding-actions">{f.areaIds.length > 0 && <button className="text-button" onClick={() => { setSelected(f.id); setSelectedRoom(f.areaIds[0]); }}>Explore in 3D →</button>}<details><summary>View evidence</summary><div className="technical-evidence">{f.evidenceIds.map(id => { const e = activeEvidence.find(item => item.id === id); return e ? <blockquote key={id}><strong>{e.sourceName}</strong><p>{e.content}</p><small>{e.id} · {e.synthetic ? 'Synthetic' : e.provenance}</small></blockquote> : null; })}</div></details></div></article>)}</div>{result && <details className="all-evidence"><summary>Technical evidence · {result.evidence.length} objects</summary><pre>{JSON.stringify(result.evidence, null, 2)}</pre></details>}</section>}
    <footer><Link href="/">← Under the Roof</Link><span>Built for the buyer. Grounded in evidence.</span></footer>
  </main>;
}
