'use client';
import { EvidenceDetails, permitSummary } from './presentation';
import { useEffect, useRef, useState } from 'react';
import { Color, Mesh, MeshBasicMaterial, OrthographicCamera, Raycaster, Scene, Vector2, WebGLRenderer } from 'three';
import { buildRoomScene, disposeRoomScene } from '../../lib/municipal/room-scene';
import type { PropertySpatialGraph } from '../../lib/municipal/spatial';
import type { MunicipalEvidence } from '../../lib/municipal/data';
import type { MunicipalFinding } from '../../lib/municipal/investigation';

export default function RoomView({ graph, evidence, findings, selectedRoom, onSelectRoom }: { graph: PropertySpatialGraph; evidence: MunicipalEvidence[]; findings: MunicipalFinding[]; selected: string | null; selectedRoom: string | null; onSelect: (id: string) => void; onSelectRoom: (id: string) => void }) {
  const host = useRef<HTMLDivElement>(null); const [renderMs, setRenderMs] = useState<number | null>(null);
  useEffect(() => { if (!host.current) return; const element = host.current; let renderer: WebGLRenderer; try { renderer = new WebGLRenderer({ antialias: true }); } catch { element.textContent = '3D preview unavailable. Use the room buttons below to inspect linked evidence.'; return; } const scene = new Scene(); scene.background = new Color('#f8f7f3'); const started = performance.now(); const group = buildRoomScene(graph, findings.flatMap(f => f.areaIds.map(area => ({ area, findingId: f.id, evidenceIds: f.evidenceIds })))); scene.add(group); setRenderMs(Math.round((performance.now() - started) * 10) / 10); for (const mesh of group.children) if (mesh instanceof Mesh && mesh.material instanceof MeshBasicMaterial && mesh.userData.area === selectedRoom) mesh.material.color.set('#c46d25'); const camera = new OrthographicCamera(-6, 6, 5, -5, 0.1, 100); camera.position.set(12, 12, 14); camera.lookAt(5, 0, 5); const resize = () => { const width = element.clientWidth || 600; renderer.setSize(width, 420); camera.left = -5 * width / 420; camera.right = 5 * width / 420; camera.updateProjectionMatrix(); renderer.render(scene, camera); }; element.appendChild(renderer.domElement); resize(); const observer = new ResizeObserver(resize); observer.observe(element); const click = (event: MouseEvent) => { const bounds = renderer.domElement.getBoundingClientRect(); const ray = new Raycaster(); ray.setFromCamera(new Vector2((event.clientX - bounds.left) / bounds.width * 2 - 1, -(event.clientY - bounds.top) / bounds.height * 2 + 1), camera); const area = ray.intersectObjects(group.children)[0]?.object.userData.area; if (area) onSelectRoom(area); }; renderer.domElement.addEventListener('click', click); return () => { observer.disconnect(); renderer.domElement.removeEventListener('click', click); disposeRoomScene(group); renderer.dispose(); renderer.domElement.remove(); }; }, [graph, findings, selectedRoom, onSelectRoom]);
  const room = graph.rooms.find(item => item.id === selectedRoom); const roomEvidence = room ? evidence.filter(item => item.areaIds?.includes(room.id) && ['floor_plan', 'listing_photo'].includes(item.sourceType)) : []; const observation = room ? evidence.find(item => item.sourceType === 'spatial_observation' && item.areaIds?.includes(room.id)) : undefined; const finding = room ? findings.find(item => item.areaIds.includes(room.id)) : undefined; const roomPermit = room ? evidence.filter(item => ['permit', 'permit_search'].includes(item.sourceType) && (finding?.evidenceIds.includes(item.id) ?? false)) : [];
  const graphObservation = graph.observations.find(o => o.area === room?.id);
  const openConnection = graphObservation && /open|opening/i.test(graphObservation.observation) && /kitchen/i.test(room?.id ?? '') && graph.connections.some(c => c.type === 'open_transition' && [c.from,c.to].includes(room!.id));
  const summary = openConnection && graphObservation.investigationSuggestion ? 'Astra identified an apparent open connection between the kitchen and dining area and recommended verifying renovation documentation.' : graphObservation?.observation.split(/(?<=[.!?])\s+/)[0] ?? 'No room-specific observation recorded.';
  return <div className="room-explorer"><div className="scene-wrap"><div ref={host} /><div className="scene-caption">{graph.rooms.length} rooms · Astra graph · Approximate / not to scale</div></div>
    <div className="room-tabs" aria-label="Select a room">{graph.rooms.map(item => <button aria-pressed={item.id === selectedRoom} className={item.id === selectedRoom ? 'selected' : ''} key={item.id} onClick={() => onSelectRoom(item.id)}>{item.label.replace(/\s*\(.*\)$/, '')}</button>)}</div>
    {room && <aside className="spatial-detail"><div className="detail-title"><span className="eyebrow">ROOM</span><h3>{room.label.replace(/\s*\(.*\)$/, '')}</h3><small>Synthetic demo imagery</small></div>
      <div className="room-summary-grid"><div><h4>Spatial observation</h4><p>{summary}</p></div><div><h4>Follow-up</h4><strong>{roomPermit.length ? 'Permit history checked' : 'Awaiting linked permit evidence'}</strong><p>{permitSummary(roomPermit)}</p></div><div><h4>Buyer action</h4><p>{finding ? 'Request renovation plans, work scope, applicable permits and final inspection records from the seller.' : graphObservation?.investigationSuggestion ?? 'No room-specific action recorded.'}</p></div></div>
      <p className="qualification">Approximate visual interpretation. Municipal search may be incomplete; no conclusion that unpermitted work occurred.</p>
      <details><summary>Technical evidence</summary><EvidenceDetails evidence={[...roomEvidence, ...(observation ? [observation] : []), ...roomPermit]} />{finding && <><h4>Original buyer finding</h4><p>{finding.title}</p><p>{finding.inference}</p><p>{finding.recommendedAction}</p></>}</details>
    </aside>}
  </div>;
}
